# Generated by Django 5.0.1 on 2024-11-15 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=200, null=True)),
                ("lastname", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "examcode",
                    models.CharField(editable=False, max_length=5, unique=True),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="cbt_app.exam",
                    ),
                ),
            ],
            options={
                "unique_together": {("email", "exam")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="answer",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="cbt_app.candidate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("candidate", "question")},
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="user",
        ),
    ]
